use clap::Parser;
use std::fmt;
use std::path::Path;

#[derive(Parser, Clone)]
#[command(
    name = "cc_matrix_channel",
    about = "Matrix channel bridge for Claude Code"
)]
pub struct Config {
    /// Matrix homeserver URL (e.g. https://matrix.example.com)
    #[arg(long, env = "MATRIX_HOMESERVER_URL")]
    pub homeserver_url: Option<String>,

    /// Matrix password for initial login — use MATRIX_PASSWORD env var.
    /// Required for first-run E2EE setup. Subsequent runs use saved session.
    #[arg(long, env = "MATRIX_PASSWORD", hide = true)]
    pub password: Option<String>,

    /// Matrix access token (fallback) — use MATRIX_ACCESS_TOKEN env var.
    /// Optional if MATRIX_PASSWORD is provided (token generated by login).
    #[arg(long, env = "MATRIX_ACCESS_TOKEN", hide = true)]
    pub access_token: Option<String>,

    /// Matrix user ID (e.g. @bot:example.com)
    #[arg(long, env = "MATRIX_USER_ID")]
    pub user_id: Option<String>,

    /// Matrix device ID hint. Auto-generated on first login if omitted.
    #[arg(long, env = "MATRIX_DEVICE_ID")]
    pub device_id: Option<String>,

    /// Path for SQLite store (E2EE keys + sync state)
    #[arg(long, env = "MATRIX_STORE_PATH", default_value = "./data/matrix_store")]
    pub store_path: String,

    /// Optional passphrase to encrypt the SQLite E2EE store on disk — use MATRIX_STORE_PASSPHRASE env var
    #[arg(long, env = "MATRIX_STORE_PASSPHRASE", hide = true)]
    pub store_passphrase: Option<String>,

    /// tmux target for the Claude Code pane this bridge is running alongside, e.g.
    /// "claude-matrix:claude-code" — see `tools/restart-matrix.sh` for the prior art this
    /// naming matches. Only consulted when a menu-answer reaction needs to be relayed.
    #[arg(
        long,
        env = "CC_MATRIX_TMUX_PANE",
        default_value = "claude-matrix:claude-code"
    )]
    pub tmux_pane: String,

    /// Kill switch for the tmux keystroke-relay path. Detecting and posting pending
    /// `AskUserQuestion`/`ExitPlanMode` prompts to Matrix always runs; actually sending a
    /// keystroke into the tmux pane only happens when this is explicitly `true`. Defaults
    /// `false` so a bad deploy of the relay logic can never touch the terminal without an
    /// operator deliberately opting in.
    #[arg(long, env = "CC_MATRIX_TMUX_ANSWERS_ENABLED", default_value_t = false)]
    pub tmux_answers_enabled: bool,
}

impl fmt::Debug for Config {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Config")
            .field("homeserver_url", &self.homeserver_url)
            .field("password", &self.password.as_ref().map(|_| "[REDACTED]"))
            .field(
                "access_token",
                &self.access_token.as_ref().map(|_| "[REDACTED]"),
            )
            .field("user_id", &self.user_id)
            .field("device_id", &self.device_id)
            .field("store_path", &self.store_path)
            .field(
                "store_passphrase",
                &self.store_passphrase.as_ref().map(|_| "[REDACTED]"),
            )
            .field("tmux_pane", &self.tmux_pane)
            .field("tmux_answers_enabled", &self.tmux_answers_enabled)
            .finish()
    }
}

impl Config {
    /// Extract the localpart from the user_id for login_username.
    /// e.g. "@claude:example.com" → "claude"
    pub fn user_localpart(&self) -> Option<&str> {
        let uid = self.user_id.as_deref()?.trim();
        let uid = uid.strip_prefix('@').unwrap_or(uid);
        Some(uid.split(':').next().unwrap_or(uid))
    }

    /// Check if Matrix credentials are configured.
    pub fn has_credentials(&self) -> bool {
        self.homeserver_url.is_some() && self.user_id.is_some()
    }
}

/// Check whether the .env file contains the minimum required credentials.
pub fn credentials_present(env_path: &Path) -> bool {
    let Ok(content) = std::fs::read_to_string(env_path) else {
        return false;
    };
    let has_homeserver = content.lines().any(|l| {
        l.starts_with("MATRIX_HOMESERVER_URL=") && l.len() > "MATRIX_HOMESERVER_URL=".len()
    });
    let has_user_id = content
        .lines()
        .any(|l| l.starts_with("MATRIX_USER_ID=") && l.len() > "MATRIX_USER_ID=".len());
    let has_auth = content.lines().any(|l| {
        (l.starts_with("MATRIX_PASSWORD=") && l.len() > "MATRIX_PASSWORD=".len())
            || (l.starts_with("MATRIX_ACCESS_TOKEN=") && l.len() > "MATRIX_ACCESS_TOKEN=".len())
    });
    has_homeserver && has_user_id && has_auth
}
